language: node_js

node_js:
  - 10

install:
  - npm install

script:
  - npm run cover

#send coverage data to coveralls
after_scripts: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"